const GAME_FRICTION = 0.975 // 1 = no friction , 0 = can't move
const PLAYER_MASS = 20
const GAME_WIDTH = 1280;
const GAME_HEIGHT = 720;
const BOUNCINESS = 1 ;  //1  = 100% bounce 

export default {GAME_FRICTION,PLAYER_MASS,GAME_WIDTH,GAME_HEIGHT,BOUNCINESS}
export {GAME_FRICTION,PLAYER_MASS,GAME_WIDTH,GAME_HEIGHT,BOUNCINESS}